# Generated by Django 5.2.13 on 2026-07-01 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_ativo_e_avaliacao_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro')], default='info', max_length=16)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('link_acao', models.CharField(blank=True, default='', max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.aluno')),
            ],
            options={
                'verbose_name': 'notificacao',
                'verbose_name_plural': 'notificacoes',
                'ordering': ('-criada_em',),
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAcessibilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tamanho_fonte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('muito-grande', 'Muito grande')], default='medio', max_length=16)),
                ('alto_contraste', models.BooleanField(default=False)),
                ('reduzir_animacoes', models.BooleanField(default=False)),
                ('sublinhar_links', models.BooleanField(default=False)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs_acessibilidade', to='app.aluno')),
            ],
            options={
                'verbose_name': 'preferencia de acessibilidade',
                'verbose_name_plural': 'preferencias de acessibilidade',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaConta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idioma', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en-US', 'English (US)')], default='pt-BR', max_length=8)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=16)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs_conta', to='app.aluno')),
            ],
            options={
                'verbose_name': 'preferencia de conta',
                'verbose_name_plural': 'preferencias de conta',
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Meu roteiro semanal', max_length=120)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('prompt_usado', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roteiro', to='app.aluno')),
            ],
            options={
                'verbose_name': 'roteiro',
                'verbose_name_plural': 'roteiros',
            },
        ),
    ]
